### ISSUE TITLE
Error message when selecting a flow to get runs' history

### ISSUE THREAD

**Issue by citqpdarcy** [DynamicsNinja/FlowExecutionHistory#12]
[Write any error info to resolve easier]

---
```
System.Exception:
XrmApplyUserFailed: Failed to create a Microsoft Dataverse system row representing user 'eeb7aaa0-9b1c-47c7-ab16-4451af741684' with code 'UserNotInActiveDirectory' and message 'User with objectId:eeb7aaa0-9b1c-47c7-ab16-4451af741684 does not exist in AD tenantId:93f7ac5d-f331-4033-98d9-afe7cbb6ce43'.
Flow Execution History
   à Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRuns(Flow flow, String status, DateTimeOffset dateFrom, DateTimeOffset dateTo)
   à Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.<>c__DisplayClass23_1.<GetFlowRuns>b__3(Flow f)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

---
- XrmToolBox Version: 1.2023.10.67
- FlowExecutionHistory Version: 1.2023.10.22
- DB Version: 9.2.23103.196
- Deployment: Online

**Comment by DynamicsNinja** [comment]
Which connection are you using while connecting to the tool? Is that Flow using a regular licence that is pooled (like Power Apps or D365) or is it per flow licence?

**Comment by citqpdarcy** [comment]
Hi Ivan,

We configured the connection using Client ID/Secret.
Does that help you?

Pascal J. Darcy
Directeur informatique
CITQ
1010, rue De Sérigny, bureau 810
Longueuil (Québec)  J4K 5G7

Tél. : 450 679-3737, poste 239
Télécopieur : 450-679-1489
Sans frais : 1 866 499-0550, poste 239

Courriel : ***@***.******@***.***>
Site internet : www.citq.info<http://www.citq.info/>

De : Ivan Ficko ***@***.***>
Envoyé : 2 novembre 2023 04:46
À : DynamicsNinja/FlowExecutionHistory ***@***.***>
Cc : Pascal Darcy ***@***.***>; Author ***@***.***>
Objet : Re: [DynamicsNinja/FlowExecutionHistory] Error message when selecting a flow to get runs' history (Issue #12)


Which connection are you using while connecting to the tool? Is that Flow using a regular licence that is pooled (like Power Apps or D365) or is it per flow licence?

-

**Comment by DynamicsNinja** [comment]
That's one piece of information that can help, but I can't reproduce the error on my side so I try to find out what could cause an error.

Everything points out on a flow that is running on the per-flow license, do you maybe use this kind of flow?

**Comment by citqpdarcy** [comment]
Yes maybe.
Dunno where to check that btw

Pascal J. Darcy
Directeur informatique
CITQ
1010, rue De Sérigny, bureau 810
Longueuil (Québec)  J4K 5G7

Tél. : 450 679-3737, poste 239
Télécopieur : 450-679-1489
Sans frais : 1 866 499-0550, poste 239

Courriel : ***@***.******@***.***>
Site internet : www.citq.info<http://www.citq.info/>

De : Ivan Ficko ***@***.***>
Envoyé : 2 novembre 2023 09:25
À : DynamicsNinja/FlowExecutionHistory ***@***.***>
Cc : Pascal Darcy ***@***.***>; Author ***@***.***>
Objet : Re: [DynamicsNinja/FlowExecutionHistory] Error message when selecting a flow to get runs' history (Issue #12)


That's one piece of information that can help, but I can't reproduce the error on my side so I try to find out what could cause an error.

Everything points out on a flow that is running on the per-flow license, do you maybe use this kind of flow?

-

**Comment by citqpdarcy** [comment]
Any news?

**Comment by DynamicsNinja** [comment]
Closing this issue due to no response within the past month. If you have further information or encounter this issue again, feel free to reopen with additional details. Thank you.
