### ISSUE TITLE
Not all flows are showing

### ISSUE THREAD

**Issue by taitandr** [DynamicsNinja/FlowExecutionHistory#13]
only around 10 flows are showing when about 50 exist within the environment, i can see these all from the environment admin page.

---
- Deployment: Online
- DB Version: 9.2.23103.244
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.9.66
- Tool Version: 1.2023.11.5

**Comment by DynamicsNinja** [comment]
Are those flows that are not showing part of the solution, because only flows inside a Dataverse solution are shown in the list?

**Comment by DynamicsNinja** [comment]
That's strange, data about flows is fetched directly from Dataverse, so everything that is not stored there will not be shown.

Can you try to execute this Fetch XML on your environment and check if all flows returned by this query?

`<fetch>
    <entity name='workflow'>
      <attribute name='workflowid' />
      <attribute name='name' />
      <filter type='and'>
        <condition attribute='category' operator='eq' value='5' />
      </filter>
    </entity>
  </fetch>`

**Comment by taitandr** [comment]
i executed that and returned 50+ items but on the tool itself i can only see 10... odd

**Comment by taitandr** [comment]
Hi, 

I would say 90% are triggered on new item created or changed via SharePoint online connector. none are suspended.

**Comment by DynamicsNinja** [comment]
The new version was released, you should now see the Sharepoint triggered flows, you can download it via XrmToolBox.

**Comment by taitandr** [comment]
Thank you, that works perfect now.
