### ISSUE TITLE
Enhancement - Column to show the Error Failures for failed runs

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#18]
Currently had to open each flow individually to check for the failures.  Instead can an additional column be shown displaying the "Error Details"

<img width="751" alt="image" src="https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/b386bcd8-697f-47b8-acfc-4662b2a5aef4">

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/de00a43f-3136-4bba-be94-19da03714b9e)

**Comment by DynamicsNinja** [comment]
That was on my mind for a while, but I didn't get much love from my side since it requires additional API calls per failed flow to get the details.

It's the best idea to add an option to toggle the error details column if needed and if it's not needed it should stay hidden so the fetch for flow runs executes faster.

**Comment by mustaqueali** [comment]
Hi @DynamicsNinja  

Can we set the Error Detail column display based only on the Status like

1. 'Failed' Status - show the column by default.
2. All and Others Statuses - we can hide it and we don't have to show the column to avoid additional API Calls.

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/c6e8f142-e706-4337-a21a-bc42ac5bfbec)

**Comment by DynamicsNinja** [comment]
The toggle for showing the error column can be found in the settings dialog.

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/7c0687f0-e22e-44ba-8e0a-2df7e3044b39)

**Comment by mustaqueali** [comment]
Great @DynamicsNinja. Let me review this and let you know! Thank you again.

**Comment by mustaqueali** [comment]
This is really helpful @DynamicsNinja. Thank you for implementing it.  I had an issue few times primarily when searching for a longer duration for multiple flows and raised a separate ticket.  Thank you.
