### ISSUE TITLE
Error column - Exceeding threshold limit 

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#19]
When changing the date filter to previous month, it showed the below failed message
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/7d61744c-8ec3-41f7-bf0e-f93e9a3cd1b4)

**Comment by DynamicsNinja** [comment]
How many failed runs do you have in the last month? Seems like you had huge numbers of failed ones.
