### ISSUE TITLE
Export Excel not including the Error Column

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#20]

**Comment by mustaqueali** [comment]
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/140eccbd-6b38-46bb-9f11-f0e37deded94)
Exported the list of failed runs to excel and the error column was missing in the excel file.

**Comment by DynamicsNinja** [comment]
Totally forgot about it, will add that
