### ISSUE TITLE
Duration column is not sorted correctly

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#22]
<img width="665" alt="Duration column is not sorted correctly" src="https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/4ed13822-79ab-4e42-b1c4-c261d028bf0a">

**Comment by DynamicsNinja** [comment]
Found out the issue 😊 sort is working just fine, but the shown duration is not working well. The problem is in the values that exceed the duration of 24h, so if flow is running for 1 day and 22h for example it's shown as 22:00:00.
