### ISSUE TITLE
Error detail shown in flow panel not displayed in the Error Column.

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#23]
Error detail shown in flow not displayed in the Error Column.

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/603d57f0-1c2a-4a66-90b7-04265a1c9617)
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/3e104757-9a78-4355-8d6f-f35b93cbb48c)

**Comment by DynamicsNinja** [comment]
Which action caused an error? So I can replicate it because it doesn't return the message in the usual structure.

**Comment by mustaqueali** [comment]
For those flows also where the Error Details pane not displayed, the error column is empty.  FYR.

**Comment by DynamicsNinja** [comment]
Can you provide me a JSON response that you get in Flow Portal for the SMS error.

Steps:
1. Open chrome dev tools (F12)
3. Navigate to Network tab
4. Type **remediation** in filter
5. Open failed run page
6. Click on remediation entry in network tab
7. Open response tab in that entry and copy the response JSON here

**Comment by mustaqueali** [comment]
Below is the response JSON for the remediation entry 
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/46927015/d9e3a67f-8c0f-48f4-9efc-cd29678a14ad)


{
    "remediationType": "ActionFailed",
    "errorSubject": "Action 'Incentivated_SMS' failed"
}

**Comment by DynamicsNinja** [comment]
There is a problem since they don't return the error message here I don't have anything to show.

**Comment by mustaqueali** [comment]
Okay @DynamicsNinja 

I checked the other flow error where the error details pane was shown and have a detailed response in that.  Hope you are showing the errorDescription.

{
    "remediationType": "ActionFailed",
    "errorSubject": "Action 'Update_Resource_[Set_Today's_Standby_to_No]' failed",
    "errorDescription": "Dual Write core application error-Unexpected character encountered while parsing value: <. Path '', line 0, position 0.",
    "operationOutputs": {
        "statusCode": 400,
        "headers": {
            "Cache-Control": "no-cache",
            "x-ms-service-request-id": "34fc78be-9216-46c4-8896-ba0c45ddf05b,3154d439-fdf3-49dc-a0e4-d947830c66bb",
            "Set-Cookie": "ARRAffinity=352fdd175ccfe2c87049eee292c392626e067edc955047c016c7ee613cb7c2c00147f6ec7070d5f17d585a426c08e7b4ef49366e3b807fdd66fcd6bafae280ff08DC38ACD020F0561439068929; path=/; secure; HttpOnly,ReqClientId=23bef34c-7839-4ec9-9002-8758a13708a2; expires=Wed, 28-Feb-2074 22:00:05 GMT; path=/; secure; HttpOnly,last_commit_time=2024-02-28 22:00:08Z; expires=Wed, 28-Feb-2024 22:01:08 GMT; path=/; secure; HttpOnly,ARRAffinity=352fdd175ccfe2c87049eee292c392626e067edc955047c016c7ee613cb7c2c00147f6ec7070d5f17d585a426c08e7b4ef49366e3b807fdd66fcd6bafae280ff08DC38ACD020F0561439068929; path=/; secure; HttpOnly",
            "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
            "REQ_ID": "3154d439-fdf3-49dc-a0e4-d947830c66bb,3154d439-fdf3-49dc-a0e4-d947830c66bb",
            "CRM.ServiceId": "framework",
            "AuthActivityId": "becb21b2-6de6-41a5-977c-f73d4fc284bb",
            "x-ms-dop-hint": "48",
            "x-ms-ratelimit-time-remaining-xrm-requests": "1,199.92",
            "x-ms-ratelimit-burst-remaining-xrm-requests": "5988",
            "OData-Version": "4.0",
            "X-Source": "1001812361271881237410210128237621501671754914418612931651214613251288521204956,190561601222551222441527685491613312015021116425131171841271139724753631501494312648",
            "Public": "OPTIONS,GET,HEAD,POST",
            "Date": "Wed, 28 Feb 2024 22:00:29 GMT",
            "Allow": "OPTIONS,GET,HEAD,POST",
            "Content-Type": "application/json; odata.metadata=full",
            "Expires": "-1",
            "Content-Length": "20303"
        },
        "body": {
            "error": {
                "code": "0x80040265",
                "message": "Dual Write core application error-Unexpected character encountered while parsing value: <. Path '', line 0, position 0.",
                "@Microsoft.PowerApps.CDS.ErrorDetails.OperationStatus": "0",
                "@Microsoft.PowerApps.CDS.ErrorDetails.SubErrorCode": "-2146233088",
                "@Microsoft.PowerApps.CDS.ErrorDetails.Plugin.ExceptionFromPluginExecute": "Microsoft.Dynamics.Integrator.DualWriteFpRuntime.Plugins.PreCommitPlugin",
                "@Microsoft.PowerApps.CDS.ErrorDetails.Plugin.ExceptionRetriable": "False",
                "@Microsoft.PowerApps.CDS.ErrorDetails.Plugin.ExceptionSource": "PluginExecution",
                "@Microsoft.PowerApps.CDS.ErrorDetails.Plugin.OriginalException": "PluginExecution",
                "@Microsoft.PowerApps.CDS.ErrorDetails.Plugin.PluginTrace": "[INF] - [2024-02-28T22:00:08.572Z] - plugin [PreCommitPlugin] invoked with the message of [InternalPipeline] for target [Microsoft.Xrm.Sdk.OrganizationRequestCollection].\r\n[INF] - [2024-02-28T22:00:08.572Z] - Tag: \r\n[INF] - [2024-02-28T22:00:08.572Z] - TransactionStatus: InProgress\r\n[INF] - [2024-02-28T22:00:08.572Z] - TransactionId: 28534562810\r\n[INF] - [2024-02-28T22:00:08.572Z] - Processing organization request collection [1]\r\n[INF] - [2024-02-28T22:00:08.572Z] - Fetching runtime config for all async entities\r\n[INF] - [2024-02-28T22:00:08.572Z] - Constructed dict for all async entities with the asyncSetupId. \r\n[INF] - [2024-02-28T22:00:08.572Z] - Check sync type for all the entities in the transaction\r\n[INF] - [2024-02-28T22:00:08.572Z] - Entity:bookableresource is enabled for liveSync\r\n[INF] - [2024-02-28T22:00:08.572Z] - Building transaction context\r\n[INF] - [2024-02-28T22:00:08.572Z] - Collecting organization requests\r\n[INF] - [2024-02-28T22:00:08.572Z] - Update of [bookableresource:4f5aedf7-cab5-ea11-a812-000d3a20f47a] with depth of 1\r\n[INF] - [2024-02-28T22:00:08.572Z] - [1] organization request(s) collected\r\n[INF] - [2024-02-28T22:00:08.572Z] - Populating runtime configuration dictionary\r\n[INF] - [2024-02-28T22:00:08.572Z] - Retrieving runtime configuration records for [1] unique entities\r\n[INF] - [2024-02-28T22:00:08.588Z] - [1] runtime configuration records are retrieved\r\n[INF] - [2024-02-28T22:00:08.588Z] - Runtime configuration dictionary [size=1] populated\r\n[INF] - [2024-02-28T22:00:08.588Z] - Populating organization configuration dictionary\r\n[INF] - [2024-02-28T22:00:08.604Z] - [0] organization configuration records are retrieved\r\n[INF] - [2024-02-28T22:00:08.604Z] - Organization configuration dictionary [size=0] populated\r\n[INF] - [2024-02-28T22:00:08.604Z] - {[bookableresource:4f5aedf7-cab5-ea11-a812-000d3a20f47a:0],[(0, 1, Update)],[wwsl_todaysstandby,bookableresourceid,useridyominame,msdyn_displayonscheduleboard,owningteam,wwsl_cdm_company,name,timezone,userid,msdyn_derivecapacity,calendarid,msdyn_enabledripscheduling,msdyn_enabledforfieldservicemobile,createdbyyominame,msdyn_endlocation,msdyn_displayonscheduleassistant,resourcetype,msdyn_timeoffapprovalrequired,msdyn_enableappointments,modifiedbyyominame,msdyn_startlocation]}\r\n[INF] - [2024-02-28T22:00:08.604Z] - Creating an Http client with 120 seconds timeout.\r\n[INF] - [2024-02-28T22:00:08.604Z] - Retrieving runtime configuration tuple\r\n[INF] - [2024-02-28T22:00:08.604Z] - Should read new secure config - False\r\n[INF] - [2024-02-28T22:00:08.604Z] - Getting Key Vault Secret [DualWriteRuntimeOriginalSalt], cache status: [44228112, 1]\r\n[INF] - [2024-02-28T22:00:08.604Z] - Retrieving current OrganizationDetail for CRM environment\r\n[INF] - [2024-02-28T22:00:08.604Z] - OrganizationId: f0d32552-6abb-ee11-a564-000d3a239f5b, TenantId: d14915af-fc35-41df-93eb-66122bf1f24a, FriendlyName: FS1CEDR02. EnironmentId: ccd97fbd-8971-ed55-b14f-9b1dc1ed6956, Geo: EMEA, UniqueName: unqf0d325526abbee11a564000d3a239\r\n[INF] - [2024-02-28T22:00:08.604Z] - AxApiVersion: 36\r\n[INF] - [2024-02-28T22:00:08.604Z] - crmServices.DestinationEnvironment is empty, setting from secure config - https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n[INF] - [2024-02-28T22:00:08.604Z] - Building transaction payload\r\n[INF] - [2024-02-28T22:00:08.604Z] - GetOperationsByRecord for 1 requests\r\n[INF] - [2024-02-28T22:00:08.604Z] - Determined operations for 1 unique records\r\n[INF] - [2024-02-28T22:00:08.604Z] - Adding bookableresource#4f5aedf7-cab5-ea11-a812-000d3a20f47a record into unique dictionary for operation type Update\r\n[INF] - [2024-02-28T22:00:08.604Z] - Adding new secure config to Cache\r\n[INF] - [2024-02-28T22:00:08.604Z] - Should read new secure config - False\r\n[INF] - [2024-02-28T22:00:08.604Z] - Getting Key Vault Secret [DualWriteRuntimeOriginalSalt], cache status: [44228112, 1]\r\n[INF] - [2024-02-28T22:00:08.619Z] - source filter: resourcetype eq '3'\r\n[INF] - [2024-02-28T22:00:08.619Z] - return value from filter: True\r\n[INF] - [2024-02-28T22:00:08.619Z] - Build Data Payload for Entity - bookableresource\r\n[INF] - [2024-02-28T22:00:08.619Z] - Destination Legal Entity : [:wwsl_cdm_company] -> bookableresource.WWSL:f575a85c-af29-41f3-9677-5beaaac3a46a -> WWSL:f575a85c-af29-41f3-9677-5beaaac3a46a\r\n[INF] - [2024-02-28T22:00:08.619Z] - {'WrkCtr Resources':{'WRKCTRID':'VG9ieSBCZWNrZXI=','WRKCTRTYPE':'SHVtYW4gUmVzb3VyY2Vz','PERSONNELNUMBERWM':''}}\r\n[INF] - [2024-02-28T22:00:08.619Z] - Adding payload of operation [Update] entity pair (bookableresource, WrkCtr Resources)\r\n[INF] - [2024-02-28T22:00:08.619Z] - Lookup Cache Size: 0, Cache Miss: 0, Cache Hit: 0\r\n[INF] - [2024-02-28T22:00:08.619Z] - Initializing outward edges of 1 nodes\r\n[INF] - [2024-02-28T22:00:08.619Z] - Performing topological sort of 1 elements\r\n[INF] - [2024-02-28T22:00:08.619Z] - Topological sort of 1 elements completed\r\n[INF] - [2024-02-28T22:00:08.619Z] - Entity bookableresource/WrkCtr Resources is dependent on 0 instances\r\n[INF] - [2024-02-28T22:00:08.619Z] - Parsing dependencies for entity bookableresource of ID 0\r\n[INF] - [2024-02-28T22:00:08.619Z] - Handling node bookableresource of ID 0 with References 0 of type Create/Update\r\n[INF] - [2024-02-28T22:00:08.619Z] - Adding bookableresource to sorted list\r\n[INF] - [2024-02-28T22:00:08.619Z] - Original entity order: WrkCtr Resources\r\n[INF] - [2024-02-28T22:00:08.619Z] - Sorted entity order: WrkCtr Resources\r\n[INF] - [2024-02-28T22:00:08.619Z] - Returning sorted CdsInboundData with 1 elements\r\n[INF] - [2024-02-28T22:00:08.619Z] - Sending transaction payload with 110 seconds for FinOps operations.\r\n[INF] - [2024-02-28T22:00:08.619Z] - Payload : {\"cdsInboundData\":\"{\\\"transactionId\\\":\\\"28534562810\\\",\\\"timeoutInSeconds\\\":110.0,\\\"cdsInboundEntityDataList\\\":[{\\\"entityName\\\":\\ ...\r\n[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ContentType  Value: application/json\r\n[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ms-dyn-caid  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ms-dyn-aid  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: x-ms-client-request-id  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: starting AcquireToken\r\n[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication token endpoint is https://login.microsoftonline.com/d14915af-fc35-41df-93eb-66122bf1f24a\r\n[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication resource is https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication type is ClientAssertionCertificateWithX5c\r\n[INF] - [2024-02-28T22:00:08.666Z] - The bearer authentication token was successfully obtained.\r\n[INF] - [2024-02-28T22:00:08.666Z] - Destination : {POST - https://fs1fodr02.sandbox.operations.eu.dynamics.com/data/DualWriteProjectConfigurations/Microsoft.Dynamics.DataEntities.WriteToEntityBatch}\r\n[INF] - [2024-02-28T22:00:29.701Z] - Response : {<html lang='en'><head><title>502 Bad Gateway</title><link type='image/x-icon' rel='shortcut icon' href='https://lcs.dynamics.com ...}\r\n[INF] - [2024-02-28T22:00:29.701Z] - ms-dyn-tenant: No value found, ms-dyn-aid: No value found\r\n[ERR] - [2024-02-28T22:00:29.701Z] - Unexpected character encountered while parsing value: <. Path '', line 0, position 0. - -    at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonTextReader.Read()\r\n   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)\r\n   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)\r\n   at Newtonsoft.Json.Linq.JObject.Parse(String json)\r\n   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.AXPayloadProvider.GetErrorMessages(Byte[] response)\r\n   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.SendPayloadToFinOps(ICrmServices crmServices, IPayloadProvider provider, Payload payload)\r\n   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.SendPayload(IPayloadProvider provider, ICrmServices crmServices, String dataPayload)\r\n   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.TrySendPayload(ICrmServices crmServices, String dataPayload, IList`1 providers, CrmPluginUnsecureConfiguration unsecureConfig, CrmPluginSecureConfiguration secureConfig, Boolean alertUser, IList`1 entityNames)\r\n[INF] - [2024-02-28T22:00:29.717Z] - AlertUser start tenant - d14915af-fc35-41df-93eb-66122bf1f24a; environment - https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n[INF] - [2024-02-28T22:00:29.858Z] - CreateNewErrorCountObject 80a5edc1-9915-4b67-9691-12543610c872\r\n[INF] - [2024-02-28T22:00:29.858Z] - UpdateCountToTable {\"PartitionKey\":\"80a5edc1-9915-4b67-9691-12543610c872\",\"RowKey\":\"Application\",\"ErrorCountArray\":\"[1,0,0,0,0,0,0,0,0,0]\",\"LastErrorTime\":\"2024-02-28T22:00:29.8584668Z\",\"StartTime\":\"2024-02-28T22:00:29.8584668Z\",\"AlertSettingTime\":\"00:15:00\",\"Threshold\":10}\r\n[INF] - [2024-02-28T22:00:29.874Z] - slots: 1,0,0,0,0,0,0,0,0,0",
                "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040265&client=platform",
                "@Microsoft.PowerApps.CDS.TraceText": "\r\n[Microsoft.Dynamics.Integrator.DualWriteFpRuntime.Plugins: Microsoft.Dynamics.Integrator.DualWriteFpRuntime.Plugins.PreCommitPlugin]\r\n[f3c3a6a5-b8cf-ee11-9078-000d3aade665: Update of bookableresource]\r\n\r\n\t\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - plugin [PreCommitPlugin] invoked with the message of [InternalPipeline] for target [Microsoft.Xrm.Sdk.OrganizationRequestCollection].\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Tag: \r\n\t[INF] - [2024-02-28T22:00:08.572Z] - TransactionStatus: InProgress\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - TransactionId: 28534562810\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Processing organization request collection [1]\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Fetching runtime config for all async entities\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Constructed dict for all async entities with the asyncSetupId. \r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Check sync type for all the entities in the transaction\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Entity:bookableresource is enabled for liveSync\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Building transaction context\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Collecting organization requests\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Update of [bookableresource:4f5aedf7-cab5-ea11-a812-000d3a20f47a] with depth of 1\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - [1] organization request(s) collected\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Populating runtime configuration dictionary\r\n\t[INF] - [2024-02-28T22:00:08.572Z] - Retrieving runtime configuration records for [1] unique entities\r\n\t[INF] - [2024-02-28T22:00:08.588Z] - [1] runtime configuration records are retrieved\r\n\t[INF] - [2024-02-28T22:00:08.588Z] - Runtime configuration dictionary [size=1] populated\r\n\t[INF] - [2024-02-28T22:00:08.588Z] - Populating organization configuration dictionary\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - [0] organization configuration records are retrieved\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Organization configuration dictionary [size=0] populated\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - {[bookableresource:4f5aedf7-cab5-ea11-a812-000d3a20f47a:0],[(0, 1, Update)],[wwsl_todaysstandby,bookableresourceid,useridyominame,msdyn_displayonscheduleboard,owningteam,wwsl_cdm_company,name,timezone,userid,msdyn_derivecapacity,calendarid,msdyn_enabledripscheduling,msdyn_enabledforfieldservicemobile,createdbyyominame,msdyn_endlocation,msdyn_displayonscheduleassistant,resourcetype,msdyn_timeoffapprovalrequired,msdyn_enableappointments,modifiedbyyominame,msdyn_startlocation]}\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Creating an Http client with 120 seconds timeout.\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Retrieving runtime configuration tuple\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Should read new secure config - False\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Getting Key Vault Secret [DualWriteRuntimeOriginalSalt], cache status: [44228112, 1]\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Retrieving current OrganizationDetail for CRM environment\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - OrganizationId: f0d32552-6abb-ee11-a564-000d3a239f5b, TenantId: d14915af-fc35-41df-93eb-66122bf1f24a, FriendlyName: FS1CEDR02. EnironmentId: ccd97fbd-8971-ed55-b14f-9b1dc1ed6956, Geo: EMEA, UniqueName: unqf0d325526abbee11a564000d3a239\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - AxApiVersion: 36\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - crmServices.DestinationEnvironment is empty, setting from secure config - https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Building transaction payload\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - GetOperationsByRecord for 1 requests\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Determined operations for 1 unique records\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Adding bookableresource#4f5aedf7-cab5-ea11-a812-000d3a20f47a record into unique dictionary for operation type Update\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Adding new secure config to Cache\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Should read new secure config - False\r\n\t[INF] - [2024-02-28T22:00:08.604Z] - Getting Key Vault Secret [DualWriteRuntimeOriginalSalt], cache status: [44228112, 1]\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - source filter: resourcetype eq '3'\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - return value from filter: True\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Build Data Payload for Entity - bookableresource\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Destination Legal Entity : [:wwsl_cdm_company] -> bookableresource.WWSL:f575a85c-af29-41f3-9677-5beaaac3a46a -> WWSL:f575a85c-af29-41f3-9677-5beaaac3a46a\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - {'WrkCtr Resources':{'WRKCTRID':'VG9ieSBCZWNrZXI=','WRKCTRTYPE':'SHVtYW4gUmVzb3VyY2Vz','PERSONNELNUMBERWM':''}}\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Adding payload of operation [Update] entity pair (bookableresource, WrkCtr Resources)\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Lookup Cache Size: 0, Cache Miss: 0, Cache Hit: 0\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Initializing outward edges of 1 nodes\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Performing topological sort of 1 elements\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Topological sort of 1 elements completed\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Entity bookableresource/WrkCtr Resources is dependent on 0 instances\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Parsing dependencies for entity bookableresource of ID 0\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Handling node bookableresource of ID 0 with References 0 of type Create/Update\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Adding bookableresource to sorted list\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Original entity order: WrkCtr Resources\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Sorted entity order: WrkCtr Resources\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Returning sorted CdsInboundData with 1 elements\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Sending transaction payload with 110 seconds for FinOps operations.\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Payload : {\"cdsInboundData\":\"{\\\"transactionId\\\":\\\"28534562810\\\",\\\"timeoutInSeconds\\\":110.0,\\\"cdsInboundEntityDataList\\\":[{\\\"entityName\\\":\\ ...\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ContentType  Value: application/json\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ms-dyn-caid  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: ms-dyn-aid  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - Request Header Info: Key: x-ms-client-request-id  Value: d3beb93c-2a6a-41c0-ac51-009b61af2f69\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: starting AcquireToken\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication token endpoint is https://login.microsoftonline.com/d14915af-fc35-41df-93eb-66122bf1f24a\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication resource is https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n\t[INF] - [2024-02-28T22:00:08.619Z] - AddAuthentication: authentication type is ClientAssertionCertificateWithX5c\r\n\t[INF] - [2024-02-28T22:00:08.666Z] - The bearer authentication token was successfully obtained.\r\n\t[INF] - [2024-02-28T22:00:08.666Z] - Destination : {POST - https://fs1fodr02.sandbox.operations.eu.dynamics.com/data/DualWriteProjectConfigurations/Microsoft.Dynamics.DataEntities.WriteToEntityBatch}\r\n\t[INF] - [2024-02-28T22:00:29.701Z] - Response : {<html lang='en'><head><title>502 Bad Gateway</title><link type='image/x-icon' rel='shortcut icon' href='https://lcs.dynamics.com ...}\r\n\t[INF] - [2024-02-28T22:00:29.701Z] - ms-dyn-tenant: No value found, ms-dyn-aid: No value found\r\n\t[ERR] - [2024-02-28T22:00:29.701Z] - Unexpected character encountered while parsing value: <. Path '', line 0, position 0. - -    at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n\t   at Newtonsoft.Json.JsonTextReader.Read()\r\n\t   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)\r\n\t   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)\r\n\t   at Newtonsoft.Json.Linq.JObject.Parse(String json)\r\n\t   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.AXPayloadProvider.GetErrorMessages(Byte[] response)\r\n\t   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.SendPayloadToFinOps(ICrmServices crmServices, IPayloadProvider provider, Payload payload)\r\n\t   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.SendPayload(IPayloadProvider provider, ICrmServices crmServices, String dataPayload)\r\n\t   at Microsoft.Dynamics.Integrator.DualWriteCore.Shared.SendTransactionPayload.TrySendPayload(ICrmServices crmServices, String dataPayload, IList`1 providers, CrmPluginUnsecureConfiguration unsecureConfig, CrmPluginSecureConfiguration secureConfig, Boolean alertUser, IList`1 entityNames)\r\n\t[INF] - [2024-02-28T22:00:29.717Z] - AlertUser start tenant - d14915af-fc35-41df-93eb-66122bf1f24a; environment - https://fs1fodr02.sandbox.operations.eu.dynamics.com\r\n\t[INF] - [2024-02-28T22:00:29.858Z] - CreateNewErrorCountObject 80a5edc1-9915-4b67-9691-12543610c872\r\n\t[INF] - [2024-02-28T22:00:29.858Z] - UpdateCountToTable {\"PartitionKey\":\"80a5edc1-9915-4b67-9691-12543610c872\",\"RowKey\":\"Application\",\"ErrorCountArray\":\"[1,0,0,0,0,0,0,0,0,0]\",\"LastErrorTime\":\"2024-02-28T22:00:29.8584668Z\",\"StartTime\":\"2024-02-28T22:00:29.8584668Z\",\"AlertSettingTime\":\"00:15:00\",\"Threshold\":10}\r\n\t[INF] - [2024-02-28T22:00:29.874Z] - slots: 1,0,0,0,0,0,0,0,0,0\r\n\t\r\n",
                "@Microsoft.PowerApps.CDS.InnerError.Message": "Dual Write core application error-Unexpected character encountered while parsing value: <. Path '', line 0, position 0."
            }
        }
    },
    "searchText": "(Dual Write core application error-Unexpected character encountered while parsing value: <. Path '', line 0, position 0.)|(0x80040265)",
    "documentationLink": {
        "id": "DocLink-UpdateRecord",
        "name": "Learn more about Microsoft Dataverse",
        "properties": {
            "description": "Known issues and limitations.",
            "url": "https://docs.microsoft.com/connectors/commondataserviceforapps/#known-issues-and-limitations"
        }
    }
}

**Comment by mustaqueali** [comment]
This ticket can be closed now. thanks @DynamicsNinja
