### ISSUE TITLE
When the flows checking more than 150, it always has this error

### ISSUE THREAD

**Issue by nkhl5** [DynamicsNinja/FlowExecutionHistory#28]
[Write any error info to resolve easier]

---
```
System.AggregateException:
One or more errors occurred.
mscorlib
- System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
- Fic.XTB.FlowExecutionHistory.Models.FlowRun.GetTriggerOutputs()
- Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetTriggerOutputsForFlowRun(FlowRun flowRun)
- Fic.XTB.FlowExecutionHistory.Services.FlowClient.<>c__DisplayClass17_0.<GetFlowRunsFromApi>b__0(FlowRun fr)
- System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
- System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
- System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

---
- XrmToolBox Version: 1.2023.12.68
- FlowExecutionHistory Version: 1.2024.4.6
- DB Version: 9.2.24041.186
- Deployment: Online

**Comment by DynamicsNinja** [comment]
Are you trying to fetch 150 flow runs or flow runs for 150 flows?

**Comment by nkhl5** [comment]
Dear Ivan,

  Thank you for your following up and I think the problem has been resolved after I updated the plugin 2 days ago.

  Attached my normal checking on our system which contain over 250 flows running.  Without your tool, I have no way to trace what’s happening at the system.

Regards,

mo

From: Ivan Ficko ***@***.***>
Date: Thursday, 25 April 2024 at 10:59
To: DynamicsNinja/FlowExecutionHistory ***@***.***>
Cc: Koon Hung Luk ***@***.***>, Author ***@***.***>
Subject: Re: [DynamicsNinja/FlowExecutionHistory] When the flows checking more than 150, it always has this error (Issue #28)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

Are you trying to fetch 150 flow runs or flow runs for 150 flows?
