### ISSUE TITLE
Error: Value cannot be null

### ISSUE THREAD

**Issue by pmolensky** [DynamicsNinja/FlowExecutionHistory#3]
I receive below error when trying to view the flow run history:
```
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRuns(Flow flow, String status, DateTimeOffset dateFrom, DateTimeOffset dateTo)
   at Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.<>c__DisplayClass18_1.<GetFlowRuns>b__3(Flow f)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

* Windows 11
* Username/password (not client secret)

does this help? Do you need any other information?

**Comment by pmolensky** [comment]
I see a mention of `datetime`. My locale is a mix of US and NL
In the tool: 
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/29775347/eda5dddc-56c9-4cfb-8364-22496599f05b)
My region settings:
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/29775347/fcdccd37-f0b3-4155-8c4e-a9369651a812)


FYI, I've tried multiple orgs and tenants. Same error on all

**Comment by pmolensky** [comment]
Thanks, I now see "You are not permitted to make flows in this 'flows'". I (should) have appropriate permissions as I can see the flows and run history from the UI. Changed login to match the owner of the flows, and also tested with a different tenant&org where I'm full admin (AD and D365). All give the same access denied error.

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/29775347/0936b8dc-6158-4c11-976d-50cddcf390ec)

**Comment by DynamicsNinja** [comment]
I managed to reproduce the error in a case where I selected a connection for one environment and on the login prompt I connected to another environment on a different tenant.

**Comment by pmolensky** [comment]
I doublechecked to make sure, I use the same creds in both connections. I try to connect to a different tenant and org, not my main tenant. Could it be the Automate API is assuming my own tenant and not correctly connecting to the clients tenant?

**Comment by DynamicsNinja** [comment]
I don't have such an account to test it out at my end, but I changed the code that it uses tenant ID while initiating a manual login popup so it could work now.

Please download the new version and test it out.

**Comment by pmolensky** [comment]
![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/29775347/6312a894-7dd8-4ea0-9644-30bced79e4aa)

**Comment by DynamicsNinja** [comment]
Which connection method do you use for XTB?

**Comment by pmolensky** [comment]
AuthType=Office365

**Comment by DynamicsNinja** [comment]
I assume it's via the connection string in this popup?

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/cd04d63b-8034-49bb-b971-d7b955422a6c)

**Comment by DynamicsNinja** [comment]
> AuthType=Office365

Also, you should definitely consider updating the connection to use a supported method since Office365 is deprecated for a while now

https://learn.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse

**Comment by pmolensky** [comment]
I knew this, should have seen this :-) I checked, it's still the result when creating a connection using the wizard.
I created a new connection using the "OAuth/MFA" option, instead of the "Connection Wizard" and now I see the flow history 🥳

**Comment by DynamicsNinja** [comment]
Glad that we found out what was causing the issue 😉
