### ISSUE TITLE
XrmToolBox.PluginsStore. The system canot find the file specified.

### ISSUE THREAD

**Issue by marvsbarnuevo** [DynamicsNinja/FlowExecutionHistory#30]
Hi!

I hope all is well on your end!

I've been using your tool - Flow Execution History, in XrmToolBox for last couple of months. Recently, I have noticed that there was an update to the tool which I updated it. However, after updating it and opening up to tool, I'm getting an issue "Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null' or one of its dependences. The system cannot find the file specified."

I tried troubleshooting the issue like using any tool - didn't encounter the same issue and I could use other tool without any issues, uninstalling/reinstalling the XrmToolBox itself. Downloading the latest version of the XrmToolBox. None of them worked unfortunately.

Would you know how I could properly fix the issue and if it is just really an isolated issue?

![flow_execution_history_error_message](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/169021258/1a922872-40b7-4656-ba4b-004ed4f84a48)

Thanks in advance!

**Comment by DynamicsNinja** [comment]
It's something related to the update of XTB so you just need to install the latest version of the toolbox or follow the steps from this blog post: https://jonasr.app/missing-xrmtoolbox-pluginsstore

**Comment by marvsbarnuevo** [comment]
Thank you! So I was doing it the wrong way - I was trying to add the missing .dll in the /AppData/Roaming/MscrmTools/XrmToolBox folder.
