### ISSUE TITLE
File or assembly not found when starting Flow Execution History (XML Toolbox.PluginsStore)

### ISSUE THREAD

**Issue by cosmic-tiger** [DynamicsNinja/FlowExecutionHistory#38]
When I start the Flow Execution History tool, I get an error message immediately.

![flowexecutionhistorymsg](https://github.com/user-attachments/assets/79f7c124-2a01-4215-9d5e-c8fe1f916c0b)

**Comment by DynamicsNinja** [comment]
That's a common issue with all new tools in XTB, please refer to issue https://github.com/DynamicsNinja/FlowExecutionHistory/issues/30 and you will find out how to resolve it.
