### ISSUE TITLE
Request: see or filter on triggerbody values

### ISSUE THREAD

**Issue by pmolensky** [DynamicsNinja/FlowExecutionHistory#5]
In the Microsoft flow history UI, you can select multiple columns to view in the listview. Is it possible to do something similar in FlowExecutionHistory? Not sure yet how it should look when selecting multiple flows, but being able to see the primary UID (when available) for the triggered record, can help debugging issues.

And/or being able to filter on this kind of info? Also not yet sure how it should look.
`customerid: aaaaa-0000-bbbbb`?
`new_entityid: ccccc-1111-ddddd`?

**Comment by DynamicsNinja** [comment]
I think that this will be really hard to achieve since you need to do a GET request per-flow run to get trigger body values which can explode when dealing with large datasets.
