### ISSUE TITLE
No flows returning

### ISSUE THREAD

**Issue by dominicMack** [DynamicsNinja/FlowExecutionHistory#6]
Managed to log in via the client secret, when trying to view all my flows to see runs, I only see 1 returning values. I have nearly 50 flows to generate emails, or sync data to LMS platforms. I am connected to the customers UAT environment. 

I only get 1 returning with data;

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/42e2b59c-2559-4227-a6bd-59d9fa73941e)

**Comment by DynamicsNinja** [comment]
If you don't see all flows on the left of the screen, those are probably outside of a solution. Flows should be INSIDE a solution to be visible in the list of flows.

**Comment by dominicMack** [comment]
sorry I meant I see all the flows in the left, what I don't see is when I click in on other flows any of the runs.

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/e9004e05-676d-450c-a2b9-1fba60fee030)

When check within powerapps can see runs

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/4cee3d39-1af5-4f59-ba10-3d4f800e1a58)

**Comment by DynamicsNinja** [comment]
Did you set the right Date From and Date To filters?

**Comment by dominicMack** [comment]
haha....right! You are correct! Working as expected now, thank you for your time! Will mark this as closed.

**Comment by dominicMack** [comment]
should I see error details;

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/9506d1ae-b7c3-495b-aad9-04a7cdcce334)

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/af2632a9-7f4e-48c6-ba4a-aa1989fd0df4)

**Comment by DynamicsNinja** [comment]
Yes, the error should be shown. The same one that you get on the flow run details page.

**Comment by dominicMack** [comment]
hmmm - doesn't seem to show on any of my failed examples.

**Comment by DynamicsNinja** [comment]
Those 2 fields should be loaded there

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/ea95aecc-89f5-457d-b1e9-f7c59289f417)

**Comment by DynamicsNinja** [comment]
Do you get "Getting error details" message when you click on Faild status?

**Comment by dominicMack** [comment]
Yes - says getting but then nothing. If I log in with specific flow that is showing as failed it shows this (no errors or error details

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/e462a295-ecf9-4534-b730-3612c526bdab)

Potentially because steps skipped and no error actually generated but just 'failed' 

I can see on a different error it now does return but doesn't return the error details 

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/405f2a74-58cd-4d19-93a6-72ab2861b1dd)

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/78d0fc7d-9b32-48f9-b51e-ac140ca0bfb8)

**Comment by DynamicsNinja** [comment]
So in the first case, the behavior is expected since the API is not returning any error details.

Not sure why you didn't get any error details in the second case. Can you please share the part where you get the error in the second flow? Is that out of the box Send email action or something custom?

**Comment by dominicMack** [comment]
custom send action using the documentcorepack connector 

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/55147732/86615f44-cecc-41d5-937b-bbf72d6ade7f)


error returned;
{"Success":true,"Return value":"The e-mail must have at least one recipient before it can be sent\r\n   at AutoMergeService.MergeService.SendEmail(IOrganizationService iservice, Entity queueItem)\r\n   at AutoMergeService.MergeService.ProcessDocuments(MergeService parent, Int32& pendingRecords)\r\nAUTOMERGEUK001|31301_production","DocumentJobId":"290eb2f7-0e45-4114-9d34-723a32ff6a1b"}

**Comment by DynamicsNinja** [comment]
Please do the following:

1. Open failed flow run

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/0a8f0b04-a5ee-4d48-a22e-72d185a3bb3b)

2. Open Developer Console (F12) and go to the Network tab, in the filter box type `/remediation`

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/cb4a0639-1ebd-4b54-9a8e-e63c9e29c442)

3. Refresh flow run details page

5. You will get one record in the grid below, click on it, go to the Response tab and please provide JSON that you go there

![image](https://github.com/DynamicsNinja/FlowExecutionHistory/assets/31212465/a6ca5cba-20e5-4da0-867e-bd7f474a5b9a)

**Comment by dominicMack** [comment]
{
    "remediationType": "ActionFailed",
    "errorSubject": "Action 'Send_email' failed",
    "operationOutputs": {
        "statusCode": 400,
        "headers": {
            "Strict-Transport-Security": "max-age=2592000",
            "Request-Context": "appId=cid-v1:a2e2298f-6e9b-42d8-bbed-d342fd4c92a0",
            "X-Custom-Info": "{\"ServiceName\":\"31301_COOproduction\",\"UniqueOrgName\":\"9d936496d73c47adb7d6d7fe675448df\",\"OrgFriendlyName\":\"COO\",\"ApiKey\":\"AFBA7E5C-8456-41E3-B96C-E3E9F6529414\"}",
            "X-Powered-By": "ASP.NET",
            "Timing-Allow-Origin": "*",
            "x-ms-apihub-cached-response": "true",
            "x-ms-apihub-obo": "false",
            "Date": "Tue, 26 Sep 2023 09:03:45 GMT",
            "Content-Length": "407",
            "Content-Type": "application/json"
        },
        "body": {
            "Success": true,
            "Return value": "The e-mail must have at least one recipient before it can be sent\r\n   at AutoMergeService.MergeService.SendEmail(IOrganizationService iservice, Entity queueItem)\r\n   at AutoMergeService.MergeService.ProcessDocuments(MergeService parent, Int32& pendingRecords)\r\nAUTOMERGEUK001|31301_COOproduction",
            "DocumentJobId": "290eb2f7-0e45-4114-9d34-723a32ff6a1b"
        }
    }
}

**Comment by DynamicsNinja** [comment]
With the new release I added that if flow fails with a custom error like Documents Core Pack action, it shows full JSON from the action response.

**Comment by dominicMack** [comment]
awesome thank you! Just checked and looks great, many thanks for turning this all around. 

1 last feature request, is it possible to do a 'select' all for flows - want to proactively use this to select all flows and then toggled on status = failed within the last week, so can easily see from a support perspective any failed flows.
