### ISSUE TITLE
Flows are grayed out

### ISSUE THREAD

**Issue by pierozek89** [DynamicsNinja/FlowExecutionHistory#9]
Hi,

I was so happy when I heard about your tool - is solves so many problems. 
Unfortunately I'm having some issue with it. I connected into my solution using Microsoft Login Control (like for other tools in XRMToolbox)

<img width="487" alt="image" src="https://github.com/DynamicsNinja/FlowExecutionHistory/assets/28830492/34df4a68-fd90-4a3a-ae21-1e899cea5c7a">

But flows are grayed out and I'm not able to select anything 

<img width="1910" alt="image" src="https://github.com/DynamicsNinja/FlowExecutionHistory/assets/28830492/01f56372-c28a-4d8f-9a98-597902580480">

What am I missing?

**Comment by DynamicsNinja** [comment]
It's because you are using Microsoft Login Control as a connection. If you use client/secret everything will work when you open the tool, otherwise, you need to press the Connect to Power Automate API button when the tool is started.

**Comment by pierozek89** [comment]
Understand, but with Connect To Power Automate API I get this message 

<img width="363" alt="image" src="https://github.com/DynamicsNinja/FlowExecutionHistory/assets/28830492/570a5a1c-4ef4-4906-849e-336c28b067ed">

**Comment by DynamicsNinja** [comment]
You must change the connection to use non deprecated one since Office365 auth is moving to OAuth. Recreate a connection using the OAuth method and in that case, you will be able to connect manually using the Connect button.

Or use a client/secret one and then you don't need to connect manually at all.

**Comment by pierozek89** [comment]
You are right. Now it works. Thank you very much
